name: 'gRPC stub builder'
description: 'Github action that build stub for JVM languages and upload to github maven repository'

inputs:
  proto_dir:
    description: 'Directory of proto'
    required: true
  group:
    description: 'Group when upload to maven repository'
    required: true
  artifact_id:
    description: 'ArtifactId when upload to maven repository'
    required: true
  version:
    description: 'Version when upload to maven repository'
    required: true
  gh_actor:
    description: 'Github maven repository upload actor'
    required: true
  gh_token:
    description: 'Github maven repository upload token'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout builder source code
      uses: actions/checkout@v3
      with:
        repository: belizwp/grpc-stub-action
        ref: feature/jvm
        path: grpc-stub-action

    - name: Prepare proto files
      shell: bash
      env:
        PROTO_DIR: ${{ inputs.proto_dir }}
      run: |
        cp $PROTO_DIR/* grpc-stub-action/src/main/proto

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17.0.3'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build
      working-directory: grpc-stub-action
      run: ./gradlew build

    - name: Publish package
      working-directory: grpc-stub-action
      run: ./gradlew publish
      env:
        GROUP: ${{ inputs.group }}
        ARTIFACT_ID: ${{ inputs.artifact_id }}
        VERSION: ${{ inputs.version }}
        GITHUB_ACTOR: ${{ inputs.gh_actor }}
        GITHUB_TOKEN: ${{ inputs.gh_token }}
